name: Bit Bare Scope Test

on:
  schedule:
    # * is a wildcard that matches any value
    # 0 0 * * * runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/dev:0.1.52m
    steps:
    - name: Creating a bare scope and start the server
      run: mkdir bare-scope && cd bare-scope && bit init --bare && bit start --port 4000 --no-browser
      continue-on-error: false
