name: Bit Bare Scope Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/ops:latest
    env:
      HOME: /home/bituser
    services:
      barescope:
        image: bitcli/bit-server:latest
        ports:
          - 3000:3000  
    steps:
    - name: Test barescope
      run: |
        sleep 120
        curl http://barescope:3000
      continue-on-error: false

