name: Testing Starter Bit.Dev

on:
  schedule:
    # * is a wildcard that matches any value
    # 0 0 * * * runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Testing teambit.community/starters/bit-dev
      run: |
        docker pull bitsrc/dev:0.1.52m
        docker run bitsrc/dev:0.1.52m /bin/bash -c "\
        bit new bit-dev my-bit-dev-ws --aspect teambit.community/starters/bit-dev && cd my-bit-dev-ws && \
        bit install && \
        bit build \
        "
      continue-on-error: false
