name: Bit Pioneers

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/dev:latest
    services:
      scope:
        image: bitcli/bit-server:latest
        ports:
          - 3000:3000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Creating a bit workspace
      run: bit init
      continue-on-error: false
