
name: Bit Bare Scope Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/ops:latest
      
    steps:
    - name: Check Home
      run: echo $HOME
    - name: Creating a bare scope
      run: mkdir bare-scope && cd bare-scope && bit init --bare
    - name: Start the server and test
      run: cd bare-scope && bit start --port 4000 --no-browser & sleep 120 && curl http://localhost:4000
      continue-on-error: false
