name: Bit Bare Scope Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/dev:latest
    env:
      HOME: /home/bituser
      
    steps:
    - name: Creating workspace
      run: mkdir my-workspace && bit init
    - name: Start a bare scope and add to workspace
      run: |
        barescope my-scope1 my-workspace
        barescope my-scope2 my-workspace
        barescope my-scope3 my-workspace
    - name: Check Bare Scope directories
      run: ls
      continue-on-error: false
