name: QuickStart Test - Hello World

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull docker image
      run: |
        docker pull bitsrc/dev:latest
    - name: Test starter
      run: |
        docker run bitsrc/dev:latest /bin/bash -c "\
        bit new hello-world my-hello-world --env teambit.community/starters/hello-world && \
        cd my-hello-world && bit run hello-world-app > log.txt && \
        sleep 20 && grep -q \"app is running on http://localhost:\" log.txt && \
        bit start > log.txt && \
        sleep 20 && grep -q \"Bit server is running on http://localhost:\" log.txt \
        "
      continue-on-error: false
