name: Testing QuickStart - Hello World

on:
  schedule:
    # * is a wildcard that matches any value
    # 0 0 * * * runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull docker image
      run: |
        docker pull bitsrc/dev:latest
    - name: Create workspace using starter
      run: |
        docker run bitsrc/dev:latest /bin/bash -c "\
        bit new hello-world my-hello-world --env teambit.community/starters/hello-world \
        "
      continue-on-error: false
